.gitignore, pom.xml, src/main/java/ch/heigvd/app/App.java, src/test/java/ch/heigvd/app/AppTest.java
=> 4 créer un projet maven

README.md
=> Begin readme redaction

pom.xml
=> Add picocli dependency in pom.xml

src/main/java/ch/heigvd/app/Main.java
=> Create class main

.idea/runConfigurations/Build.xml, .idea/runConfigurations/Clean.xml, .idea/runConfigurations/Main.xml, .idea/runConfigurations/New.xml, .idea/runConfigurations/Serve.xml, src/main/java/ch/heigvd/app/Build.java, src/main/java/ch/heigvd/app/Clean.java, src/main/java/ch/heigvd/app/Main.java, src/main/java/ch/heigvd/app/New.java, src/main/java/ch/heigvd/app/Serve.java
=> 6 create 4 sub commands (without implementation) with picocli

pom.xml, projet-bijelic_coke_mbayo_salhi.iml
With this fix everything runs smoothly :-)
=> Fix missing JUnit dependency in pom.xml

pom.xml, src/main/java/ch/heigvd/app/Clean.java, src/test/java/ch/heigvd/app/MainTest.java
=> Add clean feature and unit test

.github/workflows/maven.yml, config/config.json, config/index.md, pom.xml, src/main/java/ch/heigvd/app/Clean.java, src/test/java/ch/heigvd/app/MainTest.java
=> 25 format des pages

.github/workflows/maven.yml, .gitignore, config/config.json, pom.xml, projet-bijelic_coke_mbayo_salhi.iml
=> CI check for pull requests

pom.xml, src/main/java/ch/heigvd/app/Main.java, src/test/java/ch/heigvd/app/MainTest.java
Fix merge conflicts from #44. Should work now !
Closes #26
=> 26 affichage de la version fix merge conflicts

pom.xml, src/main/java/ch/heigvd/app/utils/JsonConverter.java, src/main/java/ch/heigvd/app/utils/MarkdownConverter.java, src/test/java/ch/heigvd/app/utils/JsonConverterTest.java, src/test/java/ch/heigvd/app/utils/MarkdownConverterTest.java
=> 22 saisie des données structurées

src/main/java/ch/heigvd/app/Build.java, src/test/java/ch/heigvd/app/BuildTest.java
=> Build command

src/main/java/ch/heigvd/app/commands/Build.java, src/main/java/ch/heigvd/app/commands/Serve.java, src/test/java/ch/heigvd/app/BuildTest.java
=> Refactor of Build command to use resolve method for paths

src/main/java/ch/heigvd/app/commands/Build.java, src/main/java/ch/heigvd/app/commands/Serve.java, src/test/java/ch/heigvd/app/BuildTest.java
=> Hotfix server stuck in loop

.github/workflows/auto-release.yml, pom.xml
=> [WIP] Add maven-javadoc-plugin

montest/sitetest/build/config.json, montest/sitetest/build/dossier/page.html, montest/sitetest/build/index.html, montest/sitetest/config.json, montest/sitetest/config.yaml, montest/sitetest/dossier/page.md, montest/sitetest/index.md, src/main/java/ch/heigvd/app/commands/Build.java, src/main/java/ch/heigvd/app/commands/Serve.java, src/main/java/utils/watchDir/WatchDir.java
=> 77 génération du site statique à la volée

pom.xml
Closes #81 
Will generate a code report in _target/jacoco-report_
=> 81 fb code coverage

pom.xml, src/assembly/assembly.xml, src/bin/static
=> 97 implement static command in shell instead of java jar

src/main/java/ch/heigvd/app/commands/Init.java, src/test/java/ch/heigvd/app/MainTest.java
=> Fix the init bug

mon/super/site/build/template/layout.html, src/main/java/ch/heigvd/app/commands/Serve.java
=> Fix bug - serve now working

src/main/java/ch/heigvd/app/Main.java, src/main/java/ch/heigvd/app/commands/Build.java, src/main/java/ch/heigvd/app/commands/Clean.java, src/main/java/ch/heigvd/app/commands/Init.java, src/main/java/ch/heigvd/app/commands/Serve.java, src/main/java/ch/heigvd/app/utils/JsonConverter.java, src/main/java/ch/heigvd/app/utils/parsers/MarkdownConverter.java, src/test/java/ch/heigvd/app/BuildTest.java
=> 105 refactor and comments

README.md
=> Add user manual
